'use strict';function t(g,l,f,h){g.f.aa(g.F,l,f,h,void 0)}function x(g,l,f,h){g.f.l?t(g,l,f,h):g.f.pb()._OnMessageFromDOM({type:"event",component:g.F,handler:l,dispatchOpts:h||null,data:f,responseId:null})}function H(g,l,f){g.f.a(g.F,l,f)}function I(g,l){for(const [f,h]of l)H(g,f,h)}window.Aa=class{constructor(g,l){this.f=g;this.F=l}xa(){}};
window.eb=class{constructor(g,l){this.Pa=g;this.Vb=l;this.A=-1;this.T=-Infinity;this.$b=()=>{this.A=-1;this.T=Date.now();this.G=!0;this.Pa();this.G=!1};this.Qa=this.G=!1}};"use strict";function J(g,l){const f=l.elementId,h=g.za(f,l);g.h.set(f,h);l.isVisible||(h.style.display="none");h.addEventListener("focus",()=>{K(g,"elem-focused",f)});h.addEventListener("blur",()=>{K(g,"elem-blurred",f)});g.R&&document.body.appendChild(h)}
function L(g,l){H(g,"get-element",f=>{const h=g.h.get(f.elementId);return l(h,f)})}function K(g,l,f){var h;h||(h={});h.elementId=f;t(g,l,h)}
window.Za=class extends self.Aa{constructor(g,l){super(g,l);this.h=new Map;this.R=!0;I(this,[["create",f=>J(this,f)],["destroy",f=>{{f=f.elementId;const h=this.h.get(f);this.R&&h.parentElement.removeChild(h);this.h.delete(f)}}],["set-visible",f=>{this.R&&(this.h.get(f.elementId).style.display=f.isVisible?"":"none")}],["update-position",f=>{if(this.R){var h=this.h.get(f.elementId);h.style.left=f.left+"px";h.style.top=f.top+"px";h.style.width=f.width+"px";h.style.height=f.height+"px";f=f.fontSize;null!==
f&&(h.style.fontSize=f+"em")}}],["update-state",f=>{{const h=this.h.get(f.elementId);this.ca(h,f)}}],["focus",f=>{{const h=this.h.get(f.elementId);f.focus?h.focus():h.blur()}}],["set-css-style",f=>{this.h.get(f.elementId).style[f.prop]=f.val}],["set-attribute",f=>{this.h.get(f.elementId).setAttribute(f.name,f.val)}],["remove-attribute",f=>{this.h.get(f.elementId).removeAttribute(f.name)}]]);L(this,f=>f)}za(){throw Error("required override");}ca(){throw Error("required override");}};"use strict";
{const g=/(iphone|ipod|ipad|macos|macintosh|mac os x)/i.test(navigator.userAgent);let l=0;function f(d,a){const c=document.createElement("script");c.async=!1;"module"===a&&(c.type="module");return d.dc?new Promise(e=>{const k="c3_resolve_"+l;++l;self[k]=e;c.textContent=d.hc+`\n\nself["${k}"]();`;document.head.appendChild(c)}):new Promise((e,k)=>{c.onload=e;c.onerror=k;c.src=d;document.head.appendChild(c)})}let h=!1,q=!1;function F(){if(!h){try{new Worker("blob://",{get type(){q=!0}})}catch(d){}h=
!0}return q}let v=new Audio;const G={"audio/webm; codecs=opus":!!v.canPlayType("audio/webm; codecs=opus"),"audio/ogg; codecs=opus":!!v.canPlayType("audio/ogg; codecs=opus"),"audio/webm; codecs=vorbis":!!v.canPlayType("audio/webm; codecs=vorbis"),"audio/ogg; codecs=vorbis":!!v.canPlayType("audio/ogg; codecs=vorbis"),"audio/mp4":!!v.canPlayType("audio/mp4"),"audio/mpeg":!!v.canPlayType("audio/mpeg")};v=null;async function y(d){d=await D(d);return(new TextDecoder("utf-8")).decode(d)}function D(d){return new Promise((a,
c)=>{const e=new FileReader;e.onload=k=>a(k.target.result);e.onerror=k=>c(k);e.readAsArrayBuffer(d)})}const B=[];let w=0;window.RealFile=window.File;const z=[],r=new Map,A=new Map;let C=0;const E=[];self.runOnStartup=function(d){if("function"!==typeof d)throw Error("runOnStartup called without a function");E.push(d)};const b=new Set(["cordova","playable-ad","instant-games"]);window.ba=class d{constructor(a){this.l=a.jc;this.I=null;this.b="";this.W=a.fc;this.i=a.Xa;this.L={};this.qa=this.Ua=null;this.S=
[];this.H=this.g=this.ta=null;this.u=-1;this.Zb=()=>this.Jb();this.Ta=[];this.c=a.Va;!this.l||"undefined"!==typeof OffscreenCanvas&&navigator.userActivation&&("module"!==this.i||F())||(this.l=!1);b.has(this.c)&&this.l&&(console.warn("[C3 runtime] Worker mode is enabled and supported, but is disabled in WebViews due to crbug.com/923007. Reverting to DOM mode."),this.l=!1);this.U=this.j=null;"html5"!==this.c&&"playable-ad"!==this.c||"file"!==location.protocol.substr(0,4)||alert("Exported games won't work until you upload them. (When running on the file: protocol, browsers block many features from working for security reasons.)");
this.a("runtime","cordova-fetch-local-file",c=>this.wb(c));this.a("runtime","create-job-worker",()=>this.xb());"cordova"===this.c?document.addEventListener("deviceready",()=>this.Ea(a)):this.Ea(a)}Ba(){return g&&"cordova"===this.c}$(){return g&&b.has(this.c)||navigator.standalone}async Ea(a){if("playable-ad"===this.c){this.j=self.c3_base64files;this.U={};await this.kb();for(let e=0,k=a.B.length;e<k;++e){var c=a.B[e].toLowerCase();this.U.hasOwnProperty(c)?a.B[e]={dc:!0,hc:this.U[c]}:this.j.hasOwnProperty(c)&&
(a.B[e]=URL.createObjectURL(this.j[c]))}}a.ac?this.b=a.ac:(c=location.origin,this.b=("null"===c?"file:///":c)+location.pathname,c=this.b.lastIndexOf("/"),-1!==c&&(this.b=this.b.substr(0,c+1)));a.lc&&(this.L=a.lc);c=new MessageChannel;this.I=c.port1;this.I.onmessage=e=>this._OnMessageFromRuntime(e.data);window.c3_addPortMessageHandler&&window.c3_addPortMessageHandler(e=>this.Gb(e));this.H=new self.bb(this);await M(this.H);"object"===typeof window.StatusBar&&window.StatusBar.hide();"object"===typeof window.AndroidFullScreen&&
window.AndroidFullScreen.immersiveMode();this.l?await this.rb(a,c.port2):await this.qb(a,c.port2)}ea(a){a=this.L.hasOwnProperty(a)?this.L[a]:a.endsWith("/workermain.js")&&this.L.hasOwnProperty("workermain.js")?this.L["workermain.js"]:"playable-ad"===this.c&&this.j.hasOwnProperty(a.toLowerCase())?this.j[a.toLowerCase()]:a;a instanceof Blob&&(a=URL.createObjectURL(a));return a}async Y(a,c,e){if(a.startsWith("blob:"))return new Worker(a,e);if(this.Ba()&&"file:"===location.protocol)return a=await this.X(this.W+
a),new Worker(URL.createObjectURL(new Blob([a],{type:"application/javascript"})),e);a=new URL(a,c);if(location.origin!==a.origin){a=await fetch(a);if(!a.ok)throw Error("failed to fetch worker script");a=await a.blob();return new Worker(URL.createObjectURL(a),e)}return new Worker(a,e)}o(){return Math.max(window.innerWidth,1)}m(){return Math.max(window.innerHeight,1)}Da(a){var c=this.H;return{baseUrl:this.b,windowInnerWidth:this.o(),windowInnerHeight:this.m(),devicePixelRatio:window.devicePixelRatio,
isFullscreen:d.Z(),projectData:a.qc,scriptsType:a.Xa,previewImageBlobs:window.cr_previewImageBlobs||this.j,previewProjectFileBlobs:window.cr_previewProjectFileBlobs,previewProjectFileSWUrls:window.cr_previewProjectFiles,swClientId:window.oc||"",exportType:a.Va,isDebug:-1<self.location.search.indexOf("debug"),ife:!!self.pc,jobScheduler:{inputPort:c.oa,outputPort:c.sa,maxNumWorkers:c.Xb},supportedAudioFormats:G,opusWasmScriptUrl:window.cr_opusWasmScriptUrl||this.W+"opus.wasm.js",opusWasmBinaryUrl:window.cr_opusWasmBinaryUrl||
this.W+"opus.wasm.wasm",isiOSCordova:this.Ba(),isiOSWebView:this.$(),isFBInstantAvailable:"undefined"!==typeof self.FBInstant}}async rb(a,c){var e=this.ea(a.kc);this.Ua=await this.Y(e,this.b,{type:this.i,name:"Runtime"});this.g=document.createElement("canvas");this.g.style.display="none";e=this.g.transferControlToOffscreen();document.body.appendChild(this.g);window.c3canvas=this.g;this.Ua.postMessage(Object.assign(this.Da(a),{type:"init-runtime",isInWorker:!0,messagePort:c,canvas:e,workerDependencyScripts:a.va||
[],engineScripts:a.B,projectScripts:a.M,mainProjectScript:a.Wa,projectScriptsStatus:self.C3_ProjectScriptsStatus}),[c,e,...N(this.H)]);this.S=z.map(k=>new k(this));this.Ca();self.c3_callFunction=(k,m)=>this.ta.sb(k,m);"preview"===this.c&&(self.goToLastErrorScript=()=>this.aa("runtime","go-to-last-error-script"))}async qb(a,c){this.g=document.createElement("canvas");this.g.style.display="none";document.body.appendChild(this.g);window.c3canvas=this.g;this.S=z.map(m=>new m(this));this.Ca();var e=a.B.map(m=>
"string"===typeof m?(new URL(m,this.b)).toString():m);Array.isArray(a.va)&&e.unshift(...a.va);e=await Promise.all(e.map(m=>this.ga(m,this.i)));await Promise.all(e.map(m=>f(m,this.i)));const k=self.C3_ProjectScriptsStatus;if("module"===this.i){e=a.Wa;const m=a.M;for(let [p,n]of m)if(n||(n=p),p===e)try{n=await this.ga(n,this.i),await f(n,this.i),"preview"!==this.c||k[p]||this.Ka(p,"main script did not run to completion")}catch(u){this.Ka(p,u)}else if("scriptsInEvents.js"===p||p.endsWith("/scriptsInEvents.js"))n=
await this.ga(n,this.i),await f(n,this.i)}else if(a.M&&0<a.M.length)try{if(await Promise.all(a.M.map(m=>f(m[1],this.i))),Object.values(k).some(m=>!m)){self.setTimeout(()=>this.La(k),100);return}}catch(m){console.error("[Preview] Error loading project scripts: ",m);self.setTimeout(()=>this.La(k),100);return}"preview"===this.c&&"object"!==typeof self.mc.nc?(this.D(),console.error("[C3 runtime] Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax."),alert("Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax.")):
(a=Object.assign(this.Da(a),{isInWorker:!1,messagePort:c,canvas:this.g,runOnStartupFunctions:E}),this.Ga(),this.qa=self.C3_CreateRuntime(a),await self.C3_InitRuntime(this.qa,a))}La(a){this.D();a=`Failed to load project script '${Object.entries(a).filter(c=>!c[1]).map(c=>c[0])[0]}'. Check all your JavaScript code has valid syntax.`;console.error("[Preview] "+a);alert(a)}Ka(a,c){this.D();console.error(`[Preview] Failed to load project main script (${a}): `,c);alert(`Failed to load project main script (${a}). Check all your JavaScript code has valid syntax. Press F12 and check the console for error details.`)}Ga(){this.D()}D(){const a=
window.bc;a&&(a.parentElement.removeChild(a),window.bc=null)}async xb(){const a=await O(this.H);return{outputPort:a,transferables:[a]}}pb(){if(this.l)throw Error("not available in worker mode");return this.qa}aa(a,c,e,k,m){this.I.postMessage({type:"event",component:a,handler:c,dispatchOpts:k||null,data:e,responseId:null},m)}cb(a,c){const e=C++,k=new Promise((m,p)=>{A.set(e,{resolve:m,reject:p})});this.I.postMessage({type:"event",component:a,handler:"js-invoke-function",dispatchOpts:null,data:c,responseId:e},
void 0);return k}["_OnMessageFromRuntime"](a){const c=a.type;if("event"===c)return this.Cb(a);if("result"===c)this.Mb(a);else if("runtime-ready"===c)this.Nb();else if("alert-error"===c)this.D(),alert(a.message);else if("creating-runtime"===c)this.Ga();else throw Error(`unknown message '${c}'`);}Cb(a){const c=a.component,e=a.handler,k=a.data,m=a.responseId;if(a=r.get(c))if(a=a.get(e)){var p=null;try{p=a(k)}catch(n){console.error(`Exception in '${c}' handler '${e}':`,n);null!==m&&this.O(m,!1,""+n);
return}if(null===m)return p;p&&p.then?p.then(n=>this.O(m,!0,n)).catch(n=>{console.error(`Rejection from '${c}' handler '${e}':`,n);this.O(m,!1,""+n)}):this.O(m,!0,p)}else console.warn(`[DOM] No handler '${e}' for component '${c}'`);else console.warn(`[DOM] No event handlers for component '${c}'`)}O(a,c,e){let k;e&&e.transferables&&(k=e.transferables);this.I.postMessage({type:"result",responseId:a,isOk:c,result:e},k)}Mb(a){const c=a.responseId,e=a.isOk;a=a.result;const k=A.get(c);e?k.resolve(a):k.reject(a);
A.delete(c)}a(a,c,e){let k=r.get(a);k||(k=new Map,r.set(a,k));if(k.has(c))throw Error(`[DOM] Component '${a}' already has handler '${c}'`);k.set(c,e)}static wa(a){if(z.includes(a))throw Error("DOM handler already added");z.push(a)}Ca(){for(const a of this.S)if("runtime"===a.F){this.ta=a;return}throw Error("cannot find runtime DOM handler");}Gb(a){this.aa("debugger","message",a)}Nb(){for(const a of this.S)a.xa()}static Z(){return!!(document.fullscreenElement||document.webkitFullscreenElement||document.mozFullScreenElement)}Ma(){-1===
this.u&&this.Ta.length&&(this.u=requestAnimationFrame(this.Zb))}ib(){-1!==this.u&&(cancelAnimationFrame(this.u),this.u=-1)}Jb(){this.u=-1;for(const a of this.Ta)a();this.Ma()}ma(){this.ta.ma()}$a(a){return/^(?:[a-z\-]+:)?\/\//.test(a)||"data:"===a.substr(0,5)||"blob:"===a.substr(0,5)}ab(a){return!this.$a(a)}async ga(a,c){return"cordova"===this.c&&"module"===c&&(a.startsWith("file:")||"file:"===location.protocol&&this.ab(a))?(a.startsWith(this.b)&&(a=a.substr(this.b.length)),a=await this.X(a),URL.createObjectURL(new Blob([a],
{type:"application/javascript"}))):a}async wb(a){const c=a.filename;switch(a.as){case "text":return await this.Ya(c);case "buffer":return await this.X(c);default:throw Error("unsupported type");}}ya(a){const c=window.cordova.file.applicationDirectory+"www/"+a.toLowerCase();return new Promise((e,k)=>{window.resolveLocalFileSystemURL(c,m=>{m.file(e,k)},k)})}async Ya(a){a=await this.ya(a);return await y(a)}da(){if(B.length&&!(8<=w)){w++;var a=B.shift();this.lb(a.filename,a.ic,a.cc)}}X(a){return new Promise((c,
e)=>{B.push({filename:a,ic:k=>{w--;this.da();c(k)},cc:k=>{w--;this.da();e(k)}});this.da()})}async lb(a,c,e){try{const k=await this.ya(a),m=await D(k);c(m)}catch(k){e(k)}}async kb(){const a=[];for(const [c,e]of Object.entries(this.j))a.push(this.jb(c,e));await Promise.all(a)}async jb(a,c){if("object"===typeof c)this.j[a]=new Blob([c.str],{type:c.type}),this.U[a]=c.str;else{let e=await this.ob(c);e||(e=this.mb(c));this.j[a]=e}}async ob(a){try{return await (await fetch(a)).blob()}catch(c){return console.warn("Failed to fetch a data: URI. Falling back to a slower workaround. This is probably because the Content Security Policy unnecessarily blocked it. Allow data: URIs in your CSP to avoid this.",
c),null}}mb(a){a=this.Rb(a);return this.hb(a.data,a.ec)}Rb(a){var c=a.indexOf(",");if(0>c)throw new URIError("expected comma in data: uri");var e=a.substring(c+1);c=a.substring(5,c).split(";");a=c[0]||"";const k=c[2];e="base64"===c[1]||"base64"===k?atob(e):decodeURIComponent(e);return{ec:a,data:e}}hb(a,c){var e=a.length;let k=e>>2,m=new Uint8Array(e),p=new Uint32Array(m.buffer,0,k),n,u;for(u=n=0;n<k;++n)p[n]=a.charCodeAt(u++)|a.charCodeAt(u++)<<8|a.charCodeAt(u++)<<16|a.charCodeAt(u++)<<24;for(e&=
3;e--;)m[u]=a.charCodeAt(u),++u;return new Blob([m],{type:c})}}}"use strict";
{const g=self.ba;function l(b){return b.sourceCapabilities&&b.sourceCapabilities.firesTouchEvents||b.originalEvent&&b.originalEvent.sourceCapabilities&&b.originalEvent.sourceCapabilities.firesTouchEvents}const f=new Map([["OSLeft","MetaLeft"],["OSRight","MetaRight"]]),h={dispatchRuntimeEvent:!0,dispatchUserScriptEvent:!0},q={dispatchUserScriptEvent:!0},F={dispatchRuntimeEvent:!0};function v(b){return new Promise((d,a)=>{const c=document.createElement("link");c.onload=()=>d(c);c.onerror=e=>a(e);c.rel=
"stylesheet";c.href=b;document.head.appendChild(c)})}function G(b){return new Promise((d,a)=>{const c=new Image;c.onload=()=>d(c);c.onerror=e=>a(e);c.src=b})}async function y(b){b=URL.createObjectURL(b);try{return await G(b)}finally{URL.revokeObjectURL(b)}}function D(b){return new Promise((d,a)=>{let c=new FileReader;c.onload=e=>d(e.target.result);c.onerror=e=>a(e);c.readAsText(b)})}async function B(b,d,a){if(!/firefox/i.test(navigator.userAgent))return await y(b);var c=await D(b);c=(new DOMParser).parseFromString(c,
"image/svg+xml");const e=c.documentElement;if(e.hasAttribute("width")&&e.hasAttribute("height")){const k=e.getAttribute("width"),m=e.getAttribute("height");if(!k.includes("%")&&!m.includes("%"))return await y(b)}e.setAttribute("width",d+"px");e.setAttribute("height",a+"px");c=(new XMLSerializer).serializeToString(c);b=new Blob([c],{type:"image/svg+xml"});return await y(b)}function w(b){do{if(b.parentNode&&b.hasAttribute("contenteditable"))return!0;b=b.parentNode}while(b);return!1}const z=new Set(["canvas",
"body","html"]);function r(b){z.has(b.target.tagName.toLowerCase())&&b.preventDefault()}function A(b){(b.metaKey||b.ctrlKey)&&b.preventDefault()}self.C3_GetSvgImageSize=async function(b){b=await y(b);if(0<b.width&&0<b.height)return[b.width,b.height];{b.style.position="absolute";b.style.left="0px";b.style.top="0px";b.style.visibility="hidden";document.body.appendChild(b);const d=b.getBoundingClientRect();document.body.removeChild(b);return[d.width,d.height]}};self.C3_RasterSvgImageBlob=async function(b,
d,a,c,e){b=await B(b,d,a);const k=document.createElement("canvas");k.width=c;k.height=e;k.getContext("2d").drawImage(b,0,0,d,a);return k};let C=!1;document.addEventListener("pause",()=>C=!0);document.addEventListener("resume",()=>C=!1);function E(){try{return window.parent&&window.parent.document.hasFocus()}catch(b){return!1}}g.wa(class extends self.Aa{constructor(b){super(b,"runtime");this.Ra=!0;this.v=-1;this.ua="any";this.Na=this.Oa=!1;this.pa=this.K=this.s=null;b.a("canvas","update-size",c=>this.Pb(c));
b.a("runtime","invoke-download",c=>this.Fb(c));b.a("runtime","raster-svg-image",c=>this.Kb(c));b.a("runtime","get-svg-image-size",c=>this.Db(c));b.a("runtime","set-target-orientation",c=>this.Ob(c));b.a("runtime","register-sw",()=>this.Lb());b.a("runtime","post-to-debugger",c=>this.Ia(c));b.a("runtime","go-to-script",c=>this.Ia(c));b.a("runtime","before-start-ticking",()=>this.vb());b.a("runtime","debug-highlight",c=>this.yb(c));b.a("runtime","enable-device-orientation",()=>this.gb());b.a("runtime",
"enable-device-motion",()=>this.fb());b.a("runtime","add-stylesheet",c=>this.tb(c));b.a("runtime","alert",c=>this.ub(c));b.a("runtime","hide-cordova-splash",()=>this.Eb());const d=new Set(["input","textarea","datalist"]);window.addEventListener("contextmenu",c=>{const e=c.target;d.has(e.tagName.toLowerCase())||w(e)||c.preventDefault()});const a=b.g;window.addEventListener("selectstart",r);window.addEventListener("gesturehold",r);a.addEventListener("selectstart",r);a.addEventListener("gesturehold",
r);window.addEventListener("touchstart",r,{passive:!1});"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",r,{passive:!1}),a.addEventListener("pointerdown",r)):a.addEventListener("touchstart",r);this.J=0;window.addEventListener("mousedown",c=>{1===c.button&&c.preventDefault()});window.addEventListener("mousewheel",A,{passive:!1});window.addEventListener("wheel",A,{passive:!1});window.addEventListener("resize",()=>this.Qb());window.addEventListener("fullscreenchange",()=>this.ha());
window.addEventListener("webkitfullscreenchange",()=>this.ha());window.addEventListener("mozfullscreenchange",()=>this.ha());window.addEventListener("fullscreenerror",c=>this.ia(c));window.addEventListener("webkitfullscreenerror",c=>this.ia(c));window.addEventListener("mozfullscreenerror",c=>this.ia(c));b.$()&&window.addEventListener("focusout",()=>{{const k=document.activeElement;if(k){var c=k.tagName.toLowerCase();var e=new Set("email number password search tel text url".split(" "));c="textarea"===
c?!0:"input"===c?e.has(k.type.toLowerCase()||"text"):w(k)}else c=!1}c||(document.scrollingElement.scrollTop=0)});this.ra=new Set;this.Yb=new WeakSet;this.Wb=!1}vb(){"cordova"===this.f.c?(document.addEventListener("pause",()=>this.la(!0)),document.addEventListener("resume",()=>this.la(!1))):document.addEventListener("visibilitychange",()=>this.la(document.hidden));return{isSuspended:!(!document.hidden&&!C)}}xa(){window.addEventListener("focus",()=>this.P("window-focus"));window.addEventListener("blur",
()=>{this.P("window-blur",{parentHasFocus:E()});this.J=0});window.addEventListener("keydown",d=>this.Ha("keydown",d));window.addEventListener("keyup",d=>this.Ha("keyup",d));window.addEventListener("dblclick",d=>this.ja("dblclick",d,h));window.addEventListener("wheel",d=>this.Hb(d));"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",d=>{this.fa(d);this.C("pointerdown",d)}),this.f.l&&"undefined"!==typeof window.onpointerrawupdate&&self===self.top?(this.K=new self.eb(()=>this.nb(),
5),this.K.Qa=!0,window.addEventListener("pointerrawupdate",d=>this.Ib(d))):window.addEventListener("pointermove",d=>this.C("pointermove",d)),window.addEventListener("pointerup",d=>this.C("pointerup",d)),window.addEventListener("pointercancel",d=>this.C("pointercancel",d))):(window.addEventListener("mousedown",d=>{this.fa(d);this.ka("pointerdown",d)}),window.addEventListener("mousemove",d=>this.ka("pointermove",d)),window.addEventListener("mouseup",d=>this.ka("pointerup",d)),window.addEventListener("touchstart",
d=>{this.fa(d);this.N("pointerdown",d)}),window.addEventListener("touchmove",d=>this.N("pointermove",d)),window.addEventListener("touchend",d=>this.N("pointerup",d)),window.addEventListener("touchcancel",d=>this.N("pointercancel",d)));const b=()=>this.ma();window.addEventListener("pointerup",b,!0);window.addEventListener("touchend",b,!0);window.addEventListener("click",b,!0);window.addEventListener("keydown",b,!0);window.addEventListener("gamepadconnected",b,!0)}P(b,d){t(this,b,d||null,F)}o(){return this.f.o()}m(){return this.f.m()}Qb(){const b=
this.o(),d=this.m();this.P("window-resize",{innerWidth:b,innerHeight:d,devicePixelRatio:window.devicePixelRatio});this.f.$()&&(-1!==this.v&&clearTimeout(this.v),this.Ja(b,d,0))}Sb(b,d,a){-1!==this.v&&clearTimeout(this.v);this.v=setTimeout(()=>this.Ja(b,d,a),48)}Ja(b,d,a){const c=this.o(),e=this.m();this.v=-1;c!=b||e!=d?this.P("window-resize",{innerWidth:c,innerHeight:e,devicePixelRatio:window.devicePixelRatio}):10>a&&this.Sb(c,e,a+1)}Ob(b){this.ua=b.targetOrientation}Tb(){const b=this.ua;if(screen.orientation&&
screen.orientation.lock)screen.orientation.lock(b).catch(d=>console.warn("[Construct 3] Failed to lock orientation: ",d));else try{let d=!1;screen.lockOrientation?d=screen.lockOrientation(b):screen.webkitLockOrientation?d=screen.webkitLockOrientation(b):screen.mozLockOrientation?d=screen.mozLockOrientation(b):screen.msLockOrientation&&(d=screen.msLockOrientation(b));d||console.warn("[Construct 3] Failed to lock orientation")}catch(d){console.warn("[Construct 3] Failed to lock orientation: ",d)}}ha(){const b=
g.Z();b&&"any"!==this.ua&&this.Tb();t(this,"fullscreenchange",{isFullscreen:b,innerWidth:this.o(),innerHeight:this.m()})}ia(b){console.warn("[Construct 3] Fullscreen request failed: ",b);t(this,"fullscreenerror",{isFullscreen:g.Z(),innerWidth:this.o(),innerHeight:this.m()})}la(b){b?this.f.ib():this.f.Ma();t(this,"visibilitychange",{hidden:b})}Ha(b,d){"Backspace"===d.key&&r(d);const a=f.get(d.code)||d.code;x(this,b,{code:a,key:d.key,which:d.which,repeat:d.repeat,altKey:d.altKey,ctrlKey:d.ctrlKey,metaKey:d.metaKey,
shiftKey:d.shiftKey,timeStamp:d.timeStamp},h)}Hb(b){t(this,"wheel",{clientX:b.clientX,clientY:b.clientY,pageX:b.pageX,pageY:b.pageY,deltaX:b.deltaX,deltaY:b.deltaY,deltaZ:b.deltaZ,deltaMode:b.deltaMode,timeStamp:b.timeStamp},h)}ja(b,d,a){l(d)||x(this,b,{button:d.button,buttons:d.buttons,clientX:d.clientX,clientY:d.clientY,pageX:d.pageX,pageY:d.pageY,timeStamp:d.timeStamp},a)}ka(b,d){if(!l(d)){var a=this.J;"pointerdown"===b&&0!==a?b="pointermove":"pointerup"===b&&0!==d.buttons&&(b="pointermove");x(this,
b,{pointerId:1,pointerType:"mouse",button:d.button,buttons:d.buttons,lastButtons:a,clientX:d.clientX,clientY:d.clientY,pageX:d.pageX,pageY:d.pageY,width:0,height:0,pressure:0,tangentialPressure:0,tiltX:0,tiltY:0,twist:0,timeStamp:d.timeStamp},h);this.J=d.buttons;this.ja(d.type,d,q)}}C(b,d){if(this.K&&"pointermove"!==b){var a=this.K;a.G||(-1!==a.A&&(self.clearTimeout(a.A),a.A=-1),a.T=Date.now())}a=0;"mouse"===d.pointerType&&(a=this.J);x(this,b,{pointerId:d.pointerId,pointerType:d.pointerType,button:d.button,
buttons:d.buttons,lastButtons:a,clientX:d.clientX,clientY:d.clientY,pageX:d.pageX,pageY:d.pageY,width:d.width||0,height:d.height||0,pressure:d.pressure||0,tangentialPressure:d.tangentialPressure||0,tiltX:d.tiltX||0,tiltY:d.tiltY||0,twist:d.twist||0,timeStamp:d.timeStamp},h);"mouse"===d.pointerType&&(a="mousemove","pointerdown"===b?a="mousedown":"pointerup"===b&&(a="mouseup"),this.ja(a,d,q),this.J=d.buttons)}Ib(b){this.pa=b;b=this.K;if(-1===b.A){var d=Date.now(),a=d-b.T,c=b.Vb;a>=c&&b.Qa?(b.T=d,b.G=
!0,b.Pa(),b.G=!1):b.A=self.setTimeout(b.$b,Math.max(c-a,4))}}nb(){this.C("pointermove",this.pa);this.pa=null}N(b,d){for(let a=0,c=d.changedTouches.length;a<c;++a){const e=d.changedTouches[a];x(this,b,{pointerId:e.identifier,pointerType:"touch",button:0,buttons:0,lastButtons:0,clientX:e.clientX,clientY:e.clientY,pageX:e.pageX,pageY:e.pageY,width:2*(e.radiusX||e.webkitRadiusX||0),height:2*(e.radiusY||e.webkitRadiusY||0),pressure:e.force||e.webkitForce||0,tangentialPressure:0,tiltX:0,tiltY:0,twist:e.rotationAngle||
0,timeStamp:d.timeStamp},h)}}fa(b){window!==window.top&&window.focus();this.Fa(b.target)&&document.activeElement&&!this.Fa(document.activeElement)&&document.activeElement.blur()}Fa(b){return!b||b===document||b===window||b===document.body||"canvas"===b.tagName.toLowerCase()}gb(){this.Oa||(this.Oa=!0,window.addEventListener("deviceorientation",b=>this.Ab(b)),window.addEventListener("deviceorientationabsolute",b=>this.Bb(b)))}fb(){this.Na||(this.Na=!0,window.addEventListener("devicemotion",b=>this.zb(b)))}Ab(b){t(this,
"deviceorientation",{absolute:!!b.absolute,alpha:b.alpha||0,beta:b.beta||0,gamma:b.gamma||0,timeStamp:b.timeStamp,webkitCompassHeading:b.webkitCompassHeading,webkitCompassAccuracy:b.webkitCompassAccuracy},h)}Bb(b){t(this,"deviceorientationabsolute",{absolute:!!b.absolute,alpha:b.alpha||0,beta:b.beta||0,gamma:b.gamma||0,timeStamp:b.timeStamp},h)}zb(b){let d=null;var a=b.acceleration;a&&(d={x:a.x||0,y:a.y||0,z:a.z||0});a=null;var c=b.accelerationIncludingGravity;c&&(a={x:c.x||0,y:c.y||0,z:c.z||0});
c=null;const e=b.rotationRate;e&&(c={alpha:e.alpha||0,beta:e.beta||0,gamma:e.gamma||0});t(this,"devicemotion",{acceleration:d,accelerationIncludingGravity:a,rotationRate:c,interval:b.interval,timeStamp:b.timeStamp},h)}Pb(b){const d=this.f.g;d.style.width=b.styleWidth+"px";d.style.height=b.styleHeight+"px";d.style.marginLeft=b.marginLeft+"px";d.style.marginTop=b.marginTop+"px";this.Ra&&(d.style.display="",this.Ra=!1)}Fb(b){const d=b.url;b=b.filename;const a=document.createElement("a"),c=document.body;
a.textContent=b;a.href=d;a.download=b;c.appendChild(a);a.click();c.removeChild(a)}async Kb(b){var d=b.imageBitmapOpts;b=await self.C3_RasterSvgImageBlob(b.blob,b.imageWidth,b.imageHeight,b.surfaceWidth,b.surfaceHeight);d=d?await createImageBitmap(b,d):await createImageBitmap(b);return{imageBitmap:d,transferables:[d]}}async Db(b){return await self.C3_GetSvgImageSize(b.blob)}async tb(b){await v(b.url)}ma(){var b=[...this.ra];this.ra.clear();if(!this.Wb)for(const d of b)(b=d.play())&&b.catch(()=>{this.Yb.has(d)||
this.ra.add(d)})}Eb(){navigator.splashscreen&&navigator.splashscreen.hide&&navigator.splashscreen.hide()}yb(b){if(b.show){this.s||(this.s=document.createElement("div"),this.s.id="inspectOutline",document.body.appendChild(this.s));var d=this.s;d.style.display="";d.style.left=b.left-1+"px";d.style.top=b.top-1+"px";d.style.width=b.width+2+"px";d.style.height=b.height+2+"px";d.textContent=b.name}else this.s&&(this.s.style.display="none")}Lb(){window.C3_RegisterSW&&window.C3_RegisterSW()}Ia(b){window.c3_postToMessagePort&&
(b.from="runtime",window.c3_postToMessagePort(b))}sb(b,d){return this.f.cb(this.F,{name:b,params:d})}ub(b){alert(b.message)}})}"use strict";async function M(g){if(g.Ub)throw Error("already initialised");g.Ub=!0;var l=g.V.ea("dispatchworker.js");g.na=await g.V.Y(l,g.b,{name:"DispatchWorker"});l=new MessageChannel;g.oa=l.port1;g.na.postMessage({type:"_init","in-port":l.port2},[l.port2]);g.sa=await O(g)}function N(g){return[g.oa,g.sa]}
async function O(g){const l=g.Sa.length;var f=g.V.ea("jobworker.js");f=await g.V.Y(f,g.b,{name:"JobWorker"+l});const h=new MessageChannel,q=new MessageChannel;g.na.postMessage({type:"_addJobWorker",port:h.port1},[h.port1]);f.postMessage({type:"init",number:l,"dispatch-port":h.port2,"output-port":q.port2},[h.port2,q.port2]);g.Sa.push(f);return q.port1}
self.bb=class{constructor(g){this.V=g;this.b=g.b;this.b="preview"===g.c?this.b+"c3/workers/":this.b+g.W;this.Xb=Math.min(navigator.hardwareConcurrency||2,16);this.na=null;this.Sa=[];this.sa=this.oa=null}};"use strict";window.C3_IsSupported&&(window.c3_runtimeInterface=new self.ba({jc:!0,kc:"workermain.js",B:["scripts/c3runtime.js"],M:[],Wa:"",Xa:"module",fc:"scripts/",va:[],Va:"html5"}));"use strict";
{function g(l){l.stopPropagation()}self.ba.wa(class extends self.Za{constructor(l){super(l,"progress-bar")}za(l,f){const h=document.createElement("progress");h.style.position="absolute";h.style.userSelect="none";h.style.webkitUserSelect="none";h.addEventListener("touchstart",g);h.addEventListener("touchmove",g);h.addEventListener("touchend",g);h.addEventListener("mousedown",g);h.addEventListener("mouseup",g);h.addEventListener("click",()=>{var q;q||(q={});q.elementId=l;x(this,"click",q)});f.id&&(h.id=
f.id);this.ca(h,f);return h}ca(l,f){l.title=f.title;const h=f.value;f=f.max;0<f&&0<=h?(l.max=f,l.value=h):(l.removeAttribute("value"),l.removeAttribute("max"))}})};
